### ISSUE TITLE
Clips does not create a clip for content copied in app

### ISSUE THREAD

**Issue by magas3000** [hezral/clips#37]
I was using DataSpell, a JetBrains IDE and anything I would copy inside the program would not show as a clip in Clips.

**Comment by hezral** [comment]
Can you run `flatpak run com.github.hezral.clips` in Terminal and try the copy action again. Then share the outputs in Terminal.

**Comment by magas3000** [comment]
flatpak run com.github.hezral.clips
Clips 1.0.6
2021-11-22 16:20:43.921607 startup
Gtk-Message: 16:20:43.954: Failed to load module "canberra-gtk-module"
2021-11-22 16:20:43.957301 open_db
Found ClipsDB [(0, 'main', '/home/orestis/.var/app/com.github.hezral.clips/cache/com.github.hezral.clips/com.github.hezral.clips.db')]
2021-11-22 16:20:44.221498 start auto-housekeeping
2021-11-22 16:20:44.221527 auto-retention-period 30
0 found for auto housekeeping
No records found for auto housekeeping
2021-11-22 16:20:44.221659 finish auto-housekeeping
2021-11-22 16:20:44.225824 start load_clips
2021-11-22 16:20:44.236656 loading 22
2021-11-22 16:20:44.246864 loading 21
Traceback (most recent call last):
  File "/app/share/com.github.hezral.clips/clips/clips_view.py", line 157, in new_clip
    self.flowbox.add(ClipsContainer(self.app, clip, app.cache_manager.cache_filedir, app.utils))
  File "/app/share/com.github.hezral.clips/clips/clips_view.py", line 354, in __init__
    self.content = UrlContainer(self.cache_file, self.type, app, self.cache_filedir)
  File "/app/share/com.github.hezral.clips/clips/clips_view.py", line 1589, in __init__
    self.content  = file.readlines()
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 0: invalid start byte
2021-11-22 16:20:44.257101 loading 20
Traceback (most recent call last):
  File "/app/share/com.github.hezral.clips/clips/clips_view.py", line 157, in new_clip
    self.flowbox.add(ClipsContainer(self.app, clip, app.cache_manager.cache_filedir, app.utils))
  File "/app/share/com.github.hezral.clips/clips/clips_view.py", line 354, in __init__
    self.content = UrlContainer(self.cache_file, self.type, app, self.cache_filedir)
  File "/app/share/com.github.hezral.clips/clips/clips_view.py", line 1589, in __init__
    self.content  = file.readlines()
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 0: invalid start byte
2021-11-22 16:20:44.267332 loading 19
2021-11-22 16:20:44.277569 loading 18
2021-11-22 16:20:44.287732 loading 17
2021-11-22 16:20:44.298001 loading 16
2021-11-22 16:20:44.308208 loading 15
2021-11-22 16:20:44.318467 loading 14
2021-11-22 16:20:44.328669 loading 13
Traceback (most recent call last):
  File "/app/share/com.github.hezral.clips/clips/clips_view.py", line 157, in new_clip
    self.flowbox.add(ClipsContainer(self.app, clip, app.cache_manager.cache_filedir, app.utils))
  File "/app/share/com.github.hezral.clips/clips/clips_view.py", line 354, in __init__
    self.content = UrlContainer(self.cache_file, self.type, app, self.cache_filedir)
  File "/app/share/com.github.hezral.clips/clips/clips_view.py", line 1589, in __init__
    self.content  = file.readlines()
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 0: invalid start byte
2021-11-22 16:20:44.338812 loading 12
Traceback (most recent call last):
  File "/app/share/com.github.hezral.clips/clips/clips_view.py", line 157, in new_clip
    self.flowbox.add(ClipsContainer(self.app, clip, app.cache_manager.cache_filedir, app.utils))
  File "/app/share/com.github.hezral.clips/clips/clips_view.py", line 354, in __init__
    self.content = UrlContainer(self.cache_file, self.type, app, self.cache_filedir)
  File "/app/share/com.github.hezral.clips/clips/clips_view.py", line 1589, in __init__
    self.content  = file.readlines()
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 0: invalid start byte
2021-11-22 16:20:44.348952 loading 11
2021-11-22 16:20:44.359191 loading 10
2021-11-22 16:20:44.369435 loading 9
2021-11-22 16:20:44.379599 loading 8
2021-11-22 16:20:44.389840 loading 7
Traceback (most recent call last):
  File "/app/share/com.github.hezral.clips/clips/clips_view.py", line 157, in new_clip
    self.flowbox.add(ClipsContainer(self.app, clip, app.cache_manager.cache_filedir, app.utils))
  File "/app/share/com.github.hezral.clips/clips/clips_view.py", line 354, in __init__
    self.content = UrlContainer(self.cache_file, self.type, app, self.cache_filedir)
  File "/app/share/com.github.hezral.clips/clips/clips_view.py", line 1589, in __init__
    self.content  = file.readlines()
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 0: invalid start byte
2021-11-22 16:20:44.399954 loading 6
2021-11-22 16:20:44.410077 loading 5
Traceback (most recent call last):
  File "/app/share/com.github.hezral.clips/clips/clips_view.py", line 157, in new_clip
    self.flowbox.add(ClipsContainer(self.app, clip, app.cache_manager.cache_filedir, app.utils))
  File "/app/share/com.github.hezral.clips/clips/clips_view.py", line 354, in __init__
    self.content = UrlContainer(self.cache_file, self.type, app, self.cache_filedir)
  File "/app/share/com.github.hezral.clips/clips/clips_view.py", line 1589, in __init__
    self.content  = file.readlines()
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 0: invalid start byte
2021-11-22 16:20:44.420206 loading 4
2021-11-22 16:20:44.430465 loading 3
2021-11-22 16:20:44.440635 loading 2
2021-11-22 16:20:44.450908 loading 1
2021-11-22 16:20:44.461080 finish load_clips
clipboard event captured: [0] DataSpell
Traceback (most recent call last):
  File "/app/share/com.github.hezral.clips/clips/cache_manager.py", line 364, in update_cache
    self.app.utils.do_webview_screenshot(uri=cache_uri, out_file_path=temp_cache_thumbnail_uri)
  File "/app/share/com.github.hezral.clips/clips/utils.py", line 1508, in do_webview_screenshot
    content = file.read()
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 0: invalid start byte
clipboard event captured: [0] DataSpell
Traceback (most recent call last):
  File "/app/share/com.github.hezral.clips/clips/cache_manager.py", line 364, in update_cache
    self.app.utils.do_webview_screenshot(uri=cache_uri, out_file_path=temp_cache_thumbnail_uri)
  File "/app/share/com.github.hezral.clips/clips/utils.py", line 1508, in do_webview_screenshot
    content = file.read()
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 0: invalid start byte
^C


I tried to copy three times from DataSpell while Clips was running through the terminal. I hope this helps you. If you need anything more from me let me know. I really enjoy your program overall.

**Comment by hezral** [comment]
Thanks, this is helpful. I think it has to do with the content itself. Would you mind showing what you copied if its not sensitive info

**Comment by hezral** [comment]
Hi, can you try with this build and see if its still happening?

Also capture the log as above but do it for just 1 event please. Thanks. 

https://github.com/hezral/clips/actions/runs/1529328585
