### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by pi43r** [hezral/clips#40]
Hi,

I don't know how much work it is or if it's even possible to make it work on wayland.
Just kindly wanted to let you know that it does not work.

```
❯ flatpak run com.github.hezral.clips
Traceback (most recent call last):
  File "/app/bin/com.github.hezral.clips", line 22, in <module>
    from clips import main
  File "/app/share/com.github.hezral.clips/clips/main.py", line 14, in <module>
    from .shake_listener import ShakeListener
  File "/app/share/com.github.hezral.clips/clips/shake_listener.py", line 11, in <module>
    from pynput import mouse
  File "/app/lib/python3.8/site-packages/pynput/__init__.py", line 40, in <module>
    from . import keyboard
  File "/app/lib/python3.8/site-packages/pynput/keyboard/__init__.py", line 31, in <module>
    backend = backend(__name__)
  File "/app/lib/python3.8/site-packages/pynput/_util/__init__.py", line 76, in backend
    raise ImportError('this platform is not supported: {}'.format(
ImportError: this platform is not supported: ('failed to acquire X connection: Bad display name ""', DisplayNameError(''))

Try one of the following resolutions:

 * Please make sure that you have an X server running, and that the DISPLAY environment variable is set correctly

```

**Comment by hezral** [comment]
Thanks but it won't work on wayland due to how clipboard works on wayland. I've been researching but so far no good solutions, mostly workarounds.
