### ISSUE TITLE
Clips Does Not Function Under Wayland Session

### ISSUE THREAD

**Issue by Schykle** [hezral/clips#41]
Hello! Hope I'm filing in the right place. First off, thanks for Clips! Hands-down the best clipboard manager I've used on Linux.

The bug I'm having is that Clips fails to launch in a Wayland session.

Followed the instructions for adding and installing Clips via the elementary remote. I'm using Fedora Silverblue 35, with the default Wayland session. Upon launching clips I get the following errors:

```
 Traceback (most recent call last):                                                                   
  File "/app/bin/com.github.hezral.clips", line 22, in <module>
    from clips import main
  File "/app/share/com.github.hezral.clips/clips/main.py", line 14, in <module>
    from .shake_listener import ShakeListener
  File "/app/share/com.github.hezral.clips/clips/shake_listener.py", line 11, in <module>
    from pynput import mouse
  File "/app/lib/python3.8/site-packages/pynput/__init__.py", line 40, in <module>
    from . import keyboard
  File "/app/lib/python3.8/site-packages/pynput/keyboard/__init__.py", line 31, in <module>
    backend = backend(__name__)
  File "/app/lib/python3.8/site-packages/pynput/_util/__init__.py", line 76, in backend
    raise ImportError('this platform is not supported: {}'.format(
ImportError: this platform is not supported: ('failed to acquire X connection: Bad display name ""', DisplayNameError(''))

Try one of the following resolutions:

 * Please make sure that you have an X server running, and that the DISPLAY environment variable is set correctly
```

Thanks again for this great app! Please let me know if there's any additional info I need to provide about my session or OS, or if there's anything I should test!

**Comment by hezral** [comment]
Hi, thanks for reporting this. Though this isn't a problem with Clips but instead of how Wayland works with clipboards and security of it. There's no solutions at the moment.
