### ISSUE TITLE
Can't copy anything [Fedora 36]

### ISSUE THREAD

**Issue by muhammadz0** [hezral/clips#47]
Here's the output with `flatpak run com.github.hezral.clips --debug`
After copying some text

```
running in debug mode
waiting for clipboard event
Traceback (most recent call last):
  File "/app/share/com.github.hezral.clips/clips/cache_manager.py", line 311, in update_cache
    data_tuple = clipboard_manager.clipboard_changed(clipboard, event)
  File "/app/share/com.github.hezral.clips/clips/clipboard_manager.py", line 75, in clipboard_changed
    clipboard_contents = self.get_clipboard_contents(clipboard, event, active_app)
  File "/app/share/com.github.hezral.clips/clips/clipboard_manager.py", line 114, in get_clipboard_contents
    if "WPS" in active_app and not "WPS" in supported_target[2]:
TypeError: argument of type 'NoneType' is not iterable
Active App: (None, None)
Traceback (most recent call last):
  File "/app/share/com.github.hezral.clips/clips/cache_manager.py", line 311, in update_cache
    data_tuple = clipboard_manager.clipboard_changed(clipboard, event)
  File "/app/share/com.github.hezral.clips/clips/clipboard_manager.py", line 75, in clipboard_changed
    clipboard_contents = self.get_clipboard_contents(clipboard, event, active_app)
  File "/app/share/com.github.hezral.clips/clips/clipboard_manager.py", line 114, in get_clipboard_contents
    if "WPS" in active_app and not "WPS" in supported_target[2]:
TypeError: argument of type 'NoneType' is not iterable
Gtk-Message: 22:49:18.896: Failed to load module "canberra-gtk-module"
Gtk-Message: 22:49:18.896: Failed to load module "pk-gtk-module"
Active App: (None, None)
Current clipboard offers formats:  8
0 text/plain
1 text/plain;charset=utf-8
Current clipboard offers formats:  8
0 text/plain
1 text/plain;charset=utf-8
```

**Comment by hezral** [comment]
Are you running it on X11 or Wayland?

**Comment by muhammadz0** [comment]
On Wayland via XWayland

**Comment by hezral** [comment]
It doesn't work on wayland. Haven't tested on xwayland either

**Comment by muhammadz0** [comment]
well it did work sometime ago

**Comment by muhammadz0** [comment]
Well, I reinstalled the app and elementary SDK, and now it doesn't show the error with `--debug`
Only this, after copying text in Firefox (system):
```
Current clipboard offers formats:  12
0 text/x-moz-url-priv
1 text/plain
2 text/plain;charset=utf-8
3 text/_moz_htmlinfo
4 text/_moz_htmlcontext
5 text/html
```

**Comment by hezral** [comment]
so, you're running it on xwayland right. technically it would work since thats x11, try running it without the --debug and see what errors are showing up.

**Comment by muhammadz0** [comment]
Ah, again:
```
Traceback (most recent call last):
  File "/app/share/com.github.hezral.clips/clips/cache_manager.py", line 311, in update_cache
    data_tuple = clipboard_manager.clipboard_changed(clipboard, event)
  File "/app/share/com.github.hezral.clips/clips/clipboard_manager.py", line 75, in clipboard_changed
    clipboard_contents = self.get_clipboard_contents(clipboard, event, active_app)
  File "/app/share/com.github.hezral.clips/clips/clipboard_manager.py", line 114, in get_clipboard_contents
    if "WPS" in active_app and not "WPS" in supported_target[2]:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by hezral** [comment]
thanks that narrows it. 
hmm are you trying to copy something in WPS Office? I havent update this part of the code for awhile and it worked when i tested it last time

**Comment by muhammadz0** [comment]
nope, Firefox

**Comment by hezral** [comment]
hmm for all apps too?

**Comment by muhammadz0** [comment]
yep, just tried Chromium (flatpak) and Nautilus

**Comment by hezral** [comment]
Ok, I'll try to reproduce this. Can you share your setup? OS, desktop environment

**Comment by muhammadz0** [comment]
Fedora Linux 36 64-bit,
GNOME 42.3,
Wayland

**Comment by hezral** [comment]
Thanks

**Comment by hezral** [comment]
Can you try moving the cache folder ~/.var/app/com.github.hezral.clips somewhere else and restart the app?

I just tried on Fedora 36, Gnome 42, X11 and it's working fine

![image](https://user-images.githubusercontent.com/762735/184323729-ec3a24ec-37a4-4c7e-b572-e97591ed3e46.png)

**Comment by muhammadxzk** [comment]
Hmm, kay!

**Comment by muhammadz0** [comment]
hmm, didn't work. I had already tried that multiple times. Also tried resetting the permissions. Didn't work

**Comment by muhammadz0** [comment]
I tried it in X11 session, and it did work, however still the same on Wayland. Can you try on Wayland?

**Comment by hezral** [comment]
Wayland won't work as-is for this app. 
I'm working on a gnome shell extension version of Clips which will work on Wayland and X11 

![image](https://user-images.githubusercontent.com/762735/184467020-46c10254-f4bb-4f0c-8022-0bf5ad620864.png)

**Comment by muhammadz0** [comment]
Sorry, I meant via XWayland

**Comment by hezral** [comment]
Which specific xwayland app did it worked with? Firefox, Chromium, Nautilus are all wayland not xwayland. 

In any case, it wouldn't have worked to begin with really since the backend fully relies on X11 and won't start in Wayland.

**Comment by muhammadz0** [comment]
ah sorry mb. Actually now that I remember, I used Code-OSS with XWayland, and it was the only app I used for Clips I think. Sorry my bad
